### ISSUE TITLE
AUR package for Arch Linux user

### ISSUE THREAD

**Issue by Hayao0819** [just-js/just#15]
I have created the PKGBUILD of just for Arch Linux to install just easily.
Please add how to install with PKGBUILD to README.
The link of PKGBUILD is [here](https://aur.archlinux.org/packages/just-js)

**Comment by billywhizz** [comment]
@Hayao0819 thanks for this! i don't have much experience with Arch. can you let me know what i need to add? maybe do a pull request with the change you want in the current README?

**Comment by Hayao0819** [comment]
Ok, I'll post pullrequest

**Comment by Hayao0819** [comment]
What do the JUST_HOME and JUST_TARGET variables mean?
What should this variable be set to when using `/usr/bin/just` ?

**Comment by billywhizz** [comment]
> What do the JUST_HOME and JUST_TARGET variables mean?
> What should this variable be set to when using `/usr/bin/just` ?

JUST_HOME is where it expects to find any shared libraries. JUST_TARGET is where it expects to download source and do building of bundled apps. i need to write some docs!

**Comment by Hayao0819** [comment]
Ok , now this packages does not set environment variables. So I will fix it after being made the docs.

**Comment by tomByrer** [comment]
Thanks!
Occasional Manjaro user here.
(Billy, Manjaro is easier to install than Arch if you're ever curious.)

**Comment by WebReflection** [comment]
what's blocking this to be part of the docs? Also, I've just flagged the module as outdated, as it's 0.1.5 instead of 0.1.12

ArchLinux is increasily popular, also thanks to SteamDeck, beside Manjaro and/or other ArchLinux flavor, so it'd be great to have just easy to use in there too.

Specially in the IoT world, Arch is also super SBC compatible, fast boot, less RAM, etc etc ... I hope this gets higher priority (writing from ArchLinux since 2014 here on every owned, and friends, Desktp/Laptops)
