### ISSUE TITLE
running `make -C just install` requires sudo

### ISSUE THREAD

**Issue by noahehall** [just-js/just#34]
env
```sh
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```

when following the setup in `just/readme.md`
the cmd `make -C just install` fails
```sh
make: Entering directory '/home/poop/git/foss/justjs/just/just'
mkdir -p /usr/local/bin
cp -f just /usr/local/bin/just
cp: cannot remove '/usr/local/bin/just': Permission denied
make: *** [Makefile:123: install] Error 1
make: Leaving directory '/home/poop/git/foss/justjs/just/just'
```

but it does work with sudo...
```sh
poop@spaceship:~/git/foss/justjs/just$ sudo !!
sudo make -C just install
make: Entering directory '/home/poop/git/foss/justjs/just/just'
mkdir -p /usr/local/bin
cp -f just /usr/local/bin/just
make: Leaving directory '/home/poop/git/foss/justjs/just/just'
```

related
- [usr/local permissions](https://unix.stackexchange.com/questions/37724/permissions-ownership-of-usr-local-bin/37726)

**Comment by mkvalor** [comment]
Hello @noahehall  I am not a dev in this repo.  Running 'make install' in almost any project will fail because the build system assumes you want to install into system-controlled directories, not to directories in the user's home.  So 'sudo' is normally expected if one runs 'make install' with no modifications.  However, this is also usually able to be overridden by changing an ENV variable.

I opened the Makefile for this project and noticed that it uses ENV variable 'INSTALL' as the prefix path for where the binary will be installed.  If you take a look yourself, you'll see that this does indeed default to a system-controlled path.  If you want to be able to install it locally, add an ENV variable assignment to with your make command like so:
`$ INSTALL=~/bin; make install`
and then it will use the path you specify as the installation dir.  Of course you can do things to make this permanent (including editing the Makefile to use your preferred default INSTALL value) if you want.

**Comment by billywhizz** [comment]
thanks @mkvalor!
