### ISSUE TITLE
Maintenance update? 

### ISSUE THREAD

**Issue by xyloflake** [just-js/just#64]
Seems like just-js has been inactively maintained since Sept 2022. Is it deprecated?

**Comment by sdr46** [comment]
> Seems like just-js has been inactively maintained since Sept 2022. Is it deprecated?

I think

**Comment by billywhizz** [comment]
i have not had time to work on it for lots of (mostly personal) reasons. i will hopefully have some time in period ahead, but i have also been working on what i think is a nicer, but similar, approach which i might release soon.

interested to know what people think. i had very little interest since release which is partly why i have not really prioritised spending any time on it in recent months, but i will hopefully have some time to spend on it or a revised version of it in the period ahead.

**Comment by xyloflake** [comment]
Alright, thank for the update and I wish you all the best!

**Comment by sdr46** [comment]
Thank for the update

**Comment by xyloflake** [comment]
@billywhizz why don't you update this info on the readme?

**Comment by xyloflake** [comment]
Sure @billywhizz , also maybe at some point in the future, I would contribute for maintainig it, but since rn I have no idea how this works, it's not possible right away. Maybe just building the docs would be the most helpful one.

**Comment by billywhizz** [comment]
@xyloflake yeah. i never went much further with it due to lack of outside interest and personal circumstances. docs/dx and cross platform defo priorities for the new thing. there's a few of us on discord now discussing things if you want to join.

**Comment by xyloflake** [comment]
I'd love to join. Where's the link?
